### ISSUE TITLE
prettier/prettier rules conflict with eslint spacing rules

### ISSUE THREAD

**Issue by sjinks** [Automattic/eslint-config-wpvip#147]
https://github.com/Automattic/vip-go-mu-plugins/blob/dependabot/npm_and_yarn/search/search-dev-tools/automattic/eslint-plugin-wpvip-0.3.0/search/search-dev-tools/src/components/collapsible-list/index.js:

![2102014312](https://user-images.githubusercontent.com/7810770/184749269-9e335439-d02a-4828-a74c-2366110e9ed5.png)

**Running `eslint --fix` results in different errors:**

![2102014313](https://user-images.githubusercontent.com/7810770/184750405-238e9854-5c2a-4518-b69e-fa1d4575accf.png)

At that, [we don't use](https://github.com/Automattic/vip-go-mu-plugins/blob/dependabot/npm_and_yarn/search/search-dev-tools/automattic/eslint-plugin-wpvip-0.3.0/search/search-dev-tools/.eslintrc.json) the prettier preset:
```
	"extends": [
		"plugin:@wordpress/eslint-plugin/recommended",
		"plugin:@automattic/wpvip/base",
		"plugin:@automattic/wpvip/react"
	],
```

**Comment by chriszarate** [comment]
I should have called this out in the README, but `plugin:@wordpress/eslint-plugin/recommended` should be removed. It is now included in `plugin:@automattic/wpvip/base`.

I pushed up some changes to https://github.com/Automattic/vip-go-mu-plugins/pull/3534 that make this change and add some lint fixes.

**Comment by chriszarate** [comment]
Closing as resolved, please reopen if there are side-effects I missed.
